<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="PRO-IND-1193" failures="1" tests="10" name="Default test" time="20.305" errors="0" timestamp="16 Apr 2024 09:51:30 GMT">
  <testcase classname="reasearch.Test2" name="method1" time="2.066"/>
  <testcase classname="reasearch.Test2" name="method1" time="2.017"/>
  <testcase classname="reasearch.Test2" name="method1" time="2.011"/>
  <testcase classname="reasearch.Test2" name="method1" time="2.016"/>
  <testcase classname="reasearch.Test2" name="method1" time="2.006"/>
  <testcase classname="reasearch.Test2" name="method1" time="2.004"/>
  <testcase classname="reasearch.Test2" name="method1" time="2.015"/>
  <testcase classname="reasearch.Test2" name="method1" time="2.008"/>
  <testcase classname="reasearch.Test2" name="method1" time="2.016"/>
  <testcase classname="reasearch.Test2" name="method1" time="2.019">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="Index 0 out of bounds for length 0">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:289)
	at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:246)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:667)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- method1 -->
</testsuite> <!-- Default test -->
